apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secret-test-web
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: secret-test-web.minikube
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: secret-test-web
            port:
              name: web